# Numba/llvmlite stack needs an older compiler for backwards compatibility.
c_compiler_version:         # [linux]
  - 7                       # [linux and x86_64]

cxx_compiler_version:       # [linux]
  - 7                       # [linux and x86_64]

dpctl:
  - 0.11.1

dpnp:
  - 0.9.0

mkl:
  - 2022.0.1

pin_run_as_build:
  dpnp: x.x
  mkl: x.x
